backend = "resized"
threshold = 10
palette = "dark"

[templates]
kitty.template = 'kitty-colors.conf'
kitty.target = '~/.config/kitty/colors-wallust.conf'

[templates.rofi]
template = 'rofi-colors.rasi'
target = '/home/florian/.cache/wallust/rofi-colors.rasi'

[templates.css]
template = 'waybar-colors.css'
target = '/home/florian/.cache/wallust/waybar-colors.css'

[templates.shell]
template = 'shell-colors.sh'
target = '/home/florian/.cache/wallust/shell-colors.sh'

